name: cowhand-node-exporter
description: Prometheus node-exporter for Cowhand
version: 0
category: Monitoring
maintainer: Daniel Dent
license: Apache 2.0
projectURL: https://github.com/danieldent/cowhand
