.catalog:
  name: Gitlab Community
  version: latest
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "git.svicloud.com"
      type: "string"
    - variable: "gitlab_omnipus_prefix"
      label: "Gitlab external_url prefix:"
      description: |
        This is needed for the docker-compose file to set the correct external_url
      default: 'http://'
      required: true
      type: "string"
      options:
        - 'https://'
        - 'http://'
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
    - variable: "https_port"
      description: "HTTPS port to expose on host. Will be used to bind TCP"
      label: "HTTPS port:"
      required: true
      default: 443
      type: "string"
    - variable: "ssh_port"
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH port:"
      required: true
      default: 22
      type: "string"

version: '2'
services:
  gitlab-server:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      interval: 30000
      strategy: recreate
  gitlab-data:
    retain_ip: true
    scale: 1
    start_on_create: true
