
alertmanager:
  restart: always
  image: ${ALERTMANAGER_IMAGE}
  log_opt:
    max-size: 1m
  labels:
    io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
  volumes:
    - "${VOL_PREFIX_ALERTMANAGER}/alertmanager"
  expose:
    - "9093"

influxdb:
  restart: always
  image: tutum/influxdb:0.10
  log_opt:
    max-size: 1m
  labels:
    io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
  volumes:
    - "${VOL_PREFIX_INFLUXDB}/data"
  expose:
    - "8083"
    - "8086"
    - "8090"
    - "8099"
  environment:
    PRE_CREATE_DB: ${INFLUXDB_DB}
    ADMIN_USER: ${INFLUXDB_USER}
    INFLUXDB_INIT_PWD: ${INFLUXDB_PASS}

grafana:
  restart: always
  image: grafana/grafana:2.6.0
  log_opt:
    max-size: 1m
  labels:
    io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
  volumes:
    - "${VOL_PREFIX_GRAFANA_DATA}/var/lib/grafana"
    - "${VOL_PREFIX_GRAFANA_LOGS}/var/log/grafana"
  expose:
    - "3000"
  environment:
    GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
  links:
    - influxdb
    - prometheus-rancher

prometheus-rancher:
  restart: always
  image: danieldent/prometheus-rancher
  log_opt:
    max-size: 1m
  labels:
    io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
    io.rancher.sidekicks: prom-rancher-sd
  volumes:
    - "${VOL_PREFIX_PROMETHEUS}/prometheus"
  volumes_from:
    - prom-rancher-sd
  expose:
    - "9090"
  memswap_limit: 0
  mem_limit: 2048000000
  command:
    - '-config.file=/etc/prometheus/prometheus.yml'
    - '-storage.local.path=/prometheus'
    - '-web.console.libraries=/etc/prometheus/console_libraries'
    - '-web.console.templates=/etc/prometheus/consoles'
    - '-alertmanager.url=http://alertmanager.rancher.internal:9093'
  links:
    - alertmanager:alertmanager

prom-rancher-sd:
  restart: always
  image: danieldent/prom-rancher-sd
  log_opt:
    max-size: 1m
  volumes:
    - "/prom-rancher-sd-data"
